// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcID-yjNFmIFkUdBP62mT8o7slUsfMIsI',
    appId: '1:792053831217:web:42bd7907b83fd5a6d46710',
    messagingSenderId: '792053831217',
    projectId: 'flutter-project-57e0a',
    authDomain: 'flutter-project-57e0a.firebaseapp.com',
    storageBucket: 'flutter-project-57e0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1dczofxaw0nzPRvhtUBB_0k6yZ99o2E',
    appId: '1:792053831217:android:d16987a02cccfcbed46710',
    messagingSenderId: '792053831217',
    projectId: 'flutter-project-57e0a',
    storageBucket: 'flutter-project-57e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPbFEgMK1UTYn7ej6WJkq9mHyEo43ujo',
    appId: '1:792053831217:ios:5c947698ecd051cad46710',
    messagingSenderId: '792053831217',
    projectId: 'flutter-project-57e0a',
    storageBucket: 'flutter-project-57e0a.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPPbFEgMK1UTYn7ej6WJkq9mHyEo43ujo',
    appId: '1:792053831217:ios:5c947698ecd051cad46710',
    messagingSenderId: '792053831217',
    projectId: 'flutter-project-57e0a',
    storageBucket: 'flutter-project-57e0a.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcID-yjNFmIFkUdBP62mT8o7slUsfMIsI',
    appId: '1:792053831217:web:5d2689390a6cb525d46710',
    messagingSenderId: '792053831217',
    projectId: 'flutter-project-57e0a',
    authDomain: 'flutter-project-57e0a.firebaseapp.com',
    storageBucket: 'flutter-project-57e0a.appspot.com',
  );
}
